import { Check, ExternalLink, Info, Monitor, Palette, Settings2, SlidersHorizontal, X } from "lucide-react";
import { useState } from "react";
import { openUrl } from "@tauri-apps/plugin-opener";
import { clearThumbnailCache, openDefaultAppsSettings } from "../services/backend";
import { checkForUpdates } from "../services/updater";
import { useAppStore } from "../stores/useAppStore";
import type { Theme } from "../types/settings";

export function SettingsModal() {
  const s = useAppStore(); const [tab, setTab] = useState("appearance"); const [checkingUpdate, setCheckingUpdate] = useState(false);
  const checkUpdate = async () => { setCheckingUpdate(true); try { await checkForUpdates(true); } finally { setCheckingUpdate(false); } };
  const tabs = [{id:"general",label:"일반",icon:Settings2},{id:"appearance",label:"모양",icon:Palette},{id:"performance",label:"성능",icon:SlidersHorizontal},{id:"about",label:"정보",icon:Info}];
  return <div className="modal-backdrop" onMouseDown={() => s.set({ settingsOpen: false })}><div className="settings-modal" onMouseDown={e => e.stopPropagation()}>
    <aside><h2>설정</h2>{tabs.map(t => <button key={t.id} className={tab===t.id?"active":""} onClick={() => setTab(t.id)}><t.icon size={17}/>{t.label}</button>)}</aside>
    <main><button className="modal-close" onClick={() => s.set({ settingsOpen: false })}><X/></button>
      {tab === "appearance" && <><h1>모양</h1><p className="settings-lead">zernia image의 화면과 분위기를 설정합니다.</p><SettingGroup title="앱 테마"><div className="theme-options">{(["system","light","dark"] as Theme[]).map(theme => <button key={theme} onClick={() => s.updateSettings({theme})} className={s.settings.theme===theme?"active":""}><Monitor/><span>{theme === "system" ? "시스템" : theme === "light" ? "라이트" : "다크"}</span>{s.settings.theme===theme && <Check size={16}/>}</button>)}</div></SettingGroup><SettingGroup title="사진 목록"><label className="slider-row"><span>기본 썸네일 크기 <b>{s.settings.thumbnailSize}px</b></span><input type="range" min="96" max="300" value={s.settings.thumbnailSize} onChange={e => s.updateSettings({thumbnailSize:+e.target.value})}/></label></SettingGroup></>}
      {tab === "general" && <><h1>일반</h1><p className="settings-lead">언어와 시작 동작을 관리합니다.</p><SettingGroup title="언어"><select value={s.settings.language} onChange={e => s.updateSettings({language:e.target.value as "ko"|"en"})}><option value="ko">한국어</option><option value="en">English</option></select></SettingGroup><SettingGroup title="사진 열기"><Toggle label="사진을 열 때 사진만 보기" checked={s.settings.openImagesImmersive} onChange={checked => s.updateSettings({openImagesImmersive:checked})}/><Toggle label="사진만 보기에서 간단한 정보 표시" checked={s.settings.showImmersiveInfo} onChange={checked => s.updateSettings({showImmersiveInfo:checked})}/></SettingGroup><SettingGroup title="자동 업데이트"><div className="setting-stack"><Toggle label="시작할 때 GitHub에서 업데이트 확인" checked={s.settings.automaticUpdates} onChange={checked => s.updateSettings({automaticUpdates:checked})}/><button className="setting-action" disabled={checkingUpdate} onClick={() => void checkUpdate()}>{checkingUpdate ? "확인 중…" : "지금 업데이트 확인"}</button></div></SettingGroup><SettingGroup title="확장명 기본 앱"><div className="file-association-setting"><div><span>지원하는 이미지 형식</span><small>JPG, PNG, WEBP, GIF, BMP, TIFF, AVIF, HEIC, JXL, ICO, QOI</small></div><button onClick={() => void openDefaultAppsSettings()}><ExternalLink/>Windows 설정 열기</button></div><p className="setting-hint">Windows 설정에서 파일 형식을 선택한 뒤 zernia image를 기본 앱으로 지정하세요.</p></SettingGroup><SettingGroup title="시작"><Toggle label="마지막 위치 기억" checked={s.settings.rememberLastLocation} onChange={checked => s.updateSettings({rememberLastLocation:checked})}/></SettingGroup><SettingGroup title="최근 기록"><Toggle label="최근 사진과 폴더 기록" checked={s.settings.rememberRecent} onChange={checked => s.updateSettings({rememberRecent:checked})}/></SettingGroup></>}
      {tab === "performance" && <><h1>성능</h1><p className="settings-lead">큰 라이브러리의 메모리와 캐시 사용량을 조절합니다.</p><SettingGroup title="메모리 캐시"><select value={s.settings.memoryCacheMb} onChange={e => s.updateSettings({memoryCacheMb:+e.target.value})}><option value="256">256 MB</option><option value="512">512 MB</option><option value="1024">1 GB</option><option value="2048">2 GB</option></select></SettingGroup><SettingGroup title="썸네일 캐시"><button className="danger-button" onClick={() => clearThumbnailCache()}>캐시 비우기</button></SettingGroup></>}
      {tab === "about" && <div className="about"><div className="about-logo">zi</div><h1>zernia image</h1><p>빠르고 아름다운 데스크톱 사진 라이브러리</p><span>버전 0.1.1 · Tauri 2</span><button className="support-button" onClick={() => void openUrl("https://buymeacoffee.com/zernia")}><ExternalLink/>개발자 후원하기</button><small>사진과 메타데이터는 기기 밖으로 전송되지 않습니다.</small></div>}
    </main>
  </div></div>;
}
function SettingGroup({title,children}:{title:string;children:React.ReactNode}) { return <section className="setting-group"><h3>{title}</h3>{children}</section>; }
function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange?:(checked:boolean)=>void}) { return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={checked} onChange={event => onChange?.(event.target.checked)} readOnly={!onChange}/></label>; }
