import { useAppStore } from "./stores/useAppStore";
import type { Language } from "./types/settings";

const ko = {
  "common.settings": "설정", "common.close": "닫기", "common.image": "사진", "common.images": "사진", "common.ready": "준비됨",
  "sidebar.navigation": "기본 탐색", "sidebar.home": "홈", "sidebar.recent": "최근 사진", "sidebar.recentDisabled": "설정에서 최근 기록이 꺼져 있습니다", "sidebar.favorites": "즐겨찾기", "sidebar.openFolder": "폴더 열기", "sidebar.recentFolders": "최근 폴더", "sidebar.removeRecent": "최근 목록에서 삭제", "sidebar.removeRecentAria": "{path} 최근 기록 삭제", "sidebar.collapse": "사이드바 접기",
  "toolbar.recent": "최근 사진", "toolbar.favorites": "즐겨찾기", "toolbar.dropped": "가져온 사진", "toolbar.library": "사진 라이브러리", "toolbar.back": "뒤로", "toolbar.forward": "앞으로", "toolbar.parent": "상위 폴더", "toolbar.move": "선택한 사진 이동", "toolbar.closeFolder": "현재 폴더 닫기", "toolbar.searchLabel": "파일명 검색", "toolbar.search": "사진 검색", "toolbar.sort": "정렬", "toolbar.sortName": "이름순", "toolbar.sortModified": "수정 날짜순", "toolbar.sortCreated": "생성 날짜순", "toolbar.sortSize": "크기순", "toolbar.sortExtension": "형식순", "toolbar.descending": "내림차순으로", "toolbar.ascending": "오름차순으로", "toolbar.refresh": "새로고침", "toolbar.list": "목록 보기", "toolbar.grid": "그리드 보기", "toolbar.details": "상세정보 패널",
  "home.dropOpen": "여기에 놓아 바로 열기", "home.dropDescription": "이미지 또는 폴더를 가져옵니다", "home.title": "사진을, 더 선명하게.", "home.description": "빠르고 조용한 사진 라이브러리.\n모든 이미지는 이 기기 안에서만 처리됩니다.", "home.browserNotice": "브라우저 미리보기에서는 폴더 선택이 비활성화됩니다.", "home.largeFolder": "대용량 폴더 최적화", "home.local": "완전한 로컬 처리", "home.dropZone": "사진 또는 폴더를 여기에 놓으세요", "home.openError": "폴더를 열 수 없습니다", "home.retry": "다시 시도", "home.photoCount": "{count}개 사진", "home.selectedCount": "{count}개 선택됨", "home.thumbnail": "썸네일",
  "gallery.empty": "검색 결과가 없습니다", "gallery.tryAnother": "다른 검색어를 입력해 보세요.", "thumb.noPreview": "미리보기 없음", "thumb.unfavorite": "즐겨찾기 해제", "thumb.favorite": "즐겨찾기 추가", "thumb.remove": "목록에서 제거", "thumb.removeKeep": "목록에서 제거 (원본 유지)",
  "details.title": "상세정보", "details.close": "상세정보 닫기", "details.select": "사진을 선택하세요", "details.selectHint": "파일과 촬영 정보를 확인할 수 있습니다.", "details.copy": "값 복사", "details.basic": "기본 정보", "details.filename": "파일명", "details.format": "형식", "details.size": "크기", "details.path": "경로", "details.image": "이미지", "details.resolution": "해상도", "details.color": "색상 형식", "details.camera": "카메라", "details.maker": "제조사", "details.model": "모델", "details.lens": "렌즈", "details.capture": "촬영", "details.shutter": "셔터", "details.aperture": "조리개", "details.focal": "초점 거리",
  "settings.general": "일반", "settings.appearance": "모양", "settings.performance": "성능", "settings.about": "정보", "settings.appearanceLead": "zernia image의 화면과 분위기를 설정합니다.", "settings.theme": "앱 테마", "settings.system": "시스템", "settings.light": "라이트", "settings.dark": "다크", "settings.photoList": "사진 목록", "settings.thumbnailSize": "기본 썸네일 크기", "settings.generalLead": "언어와 시작 동작을 관리합니다.", "settings.language": "언어", "settings.photoOpen": "사진 열기", "settings.openImmersive": "사진을 열 때 사진만 보기", "settings.showInfo": "사진만 보기에서 간단한 정보 표시", "settings.navigation": "사진 이동", "settings.loop": "마지막 사진 다음에 첫 사진으로 순환", "settings.loopHint": "끄면 첫 사진과 마지막 사진에서 더 이상 이동하지 않습니다.", "settings.updates": "자동 업데이트", "settings.autoUpdate": "시작할 때 GitHub에서 업데이트 확인", "settings.checking": "확인 중…", "settings.checkNow": "지금 업데이트 확인", "settings.defaultApp": "기본 앱", "settings.windowsPhoto": "Windows 기본 사진 앱", "settings.windowsPhotoHint": "Windows 설정에서 이 앱을 기본 사진 뷰어로 선택할 수 있습니다.", "settings.setDefault": "기본 사진 뷰어로 설정", "settings.associationHint": "JPG, PNG, APNG, WebP, AVIF, GIF, BMP, TIFF, ICO 파일 연결은 설치할 때 등록됩니다.", "settings.startup": "시작", "settings.rememberLocation": "마지막 위치 기억", "settings.history": "최근 기록", "settings.rememberRecent": "최근 사진과 폴더 기록", "settings.performanceLead": "큰 라이브러리의 메모리와 캐시 사용량을 조절합니다.", "settings.memory": "메모리 캐시", "settings.thumbnailCache": "앱 캐시", "settings.cacheUsage": "현재 {files}개 파일 · {size}", "settings.clearCache": "전체 캐시 삭제", "settings.clearingCache": "삭제 중…", "settings.cacheCleared": "캐시를 삭제했습니다.", "settings.cacheError": "캐시를 삭제하지 못했습니다.\n{details}", "settings.aboutDescription": "빠르고 아름다운 데스크톱 사진 라이브러리", "settings.version": "버전 0.1.7 · Tauri 2", "settings.support": "개발자 후원하기", "settings.privacy": "사진과 메타데이터는 기기 밖으로 전송되지 않습니다.",
  "settings.animationControls": "움짤 재생 표시줄 표시", "settings.tabDetails": "Tab 키로 상세정보 열기/닫기",
  "viewer.restore": "원래 화면으로", "viewer.minimize": "최소화", "viewer.maximize": "최대화 또는 복원", "viewer.exit": "앱 종료", "viewer.close": "뷰어 닫기", "viewer.previous": "이전 사진", "viewer.next": "다음 사진", "viewer.firstFrame": "첫 프레임", "viewer.previousFrame": "이전 프레임", "viewer.pause": "일시정지 (Space)", "viewer.play": "재생 (Space)", "viewer.nextFrame": "다음 프레임", "viewer.lastFrame": "마지막 프레임", "viewer.frameSeek": "프레임 탐색", "viewer.frameNumber": "프레임 번호", "viewer.frames": "프레임", "viewer.immersive": "사진만 보기", "viewer.fit": "화면 맞춤", "viewer.zoomOut": "축소", "viewer.zoomIn": "확대", "viewer.rotate": "회전", "viewer.flip": "좌우 반전", "viewer.info": "사진 정보", "viewer.fileSize": "파일 크기", "viewer.modified": "수정한 날짜", "viewer.imageInfo": "이미지 정보",
  "dialog.chooseFolder": "사진 폴더 선택", "dialog.chooseDestination": "사진을 이동할 폴더 선택", "error.moveSome": "일부 사진을 이동하지 못했습니다.\n{details}", "error.move": "사진을 이동하지 못했습니다.\n{details}", "error.noImages": "지원하는 이미지 파일을 찾지 못했습니다.", "error.openDropped": "가져온 항목을 열 수 없습니다.\n{details}", "update.current": "현재 최신 버전을 사용하고 있습니다.", "update.available": "새 버전 {version}을 사용할 수 있습니다.\n지금 다운로드하고 설치할까요?", "update.error": "업데이트를 확인할 수 없습니다.\n{details}"
} as const;

export type TranslationKey = keyof typeof ko;
type Dictionary = Record<TranslationKey, string>;

const en: Dictionary = {
  ...ko,
  "common.settings":"Settings","common.close":"Close","common.image":"Image","common.images":"Photos","common.ready":"Ready",
  "sidebar.navigation":"Primary navigation","sidebar.home":"Home","sidebar.recent":"Recent photos","sidebar.recentDisabled":"Recent history is disabled in Settings","sidebar.favorites":"Favorites","sidebar.openFolder":"Open folder","sidebar.recentFolders":"Recent folders","sidebar.removeRecent":"Remove from recent list","sidebar.removeRecentAria":"Remove {path} from recent history","sidebar.collapse":"Collapse sidebar",
  "toolbar.recent":"Recent photos","toolbar.favorites":"Favorites","toolbar.dropped":"Imported photos","toolbar.library":"Photo library","toolbar.back":"Back","toolbar.forward":"Forward","toolbar.parent":"Parent folder","toolbar.move":"Move selected photos","toolbar.closeFolder":"Close current folder","toolbar.searchLabel":"Search by filename","toolbar.search":"Search photos","toolbar.sort":"Sort","toolbar.sortName":"Name","toolbar.sortModified":"Date modified","toolbar.sortCreated":"Date created","toolbar.sortSize":"Size","toolbar.sortExtension":"Format","toolbar.descending":"Descending","toolbar.ascending":"Ascending","toolbar.refresh":"Refresh","toolbar.list":"List view","toolbar.grid":"Grid view","toolbar.details":"Details panel",
  "home.dropOpen":"Drop here to open","home.dropDescription":"Import images or a folder","home.title":"See every photo clearly.","home.description":"A fast, quiet photo library.\nEvery image stays on this device.","home.browserNotice":"Folder selection is disabled in browser preview.","home.largeFolder":"Optimized for large folders","home.local":"Fully local processing","home.dropZone":"Drop photos or a folder here","home.openError":"Could not open folder","home.retry":"Try again","home.photoCount":"{count} photos","home.selectedCount":"{count} selected","home.thumbnail":"Thumbnail",
  "gallery.empty":"No results","gallery.tryAnother":"Try another search term.","thumb.noPreview":"No preview","thumb.unfavorite":"Remove from favorites","thumb.favorite":"Add to favorites","thumb.remove":"Remove from list","thumb.removeKeep":"Remove from list (keep original)",
  "details.title":"Details","details.close":"Close details","details.select":"Select a photo","details.selectHint":"View file and capture information.","details.copy":"Copy value","details.basic":"Basic information","details.filename":"Filename","details.format":"Format","details.size":"Size","details.path":"Path","details.image":"Image","details.resolution":"Resolution","details.color":"Color format","details.camera":"Camera","details.maker":"Make","details.model":"Model","details.lens":"Lens","details.capture":"Capture","details.shutter":"Shutter","details.aperture":"Aperture","details.focal":"Focal length",
  "settings.general":"General","settings.appearance":"Appearance","settings.performance":"Performance","settings.about":"About","settings.appearanceLead":"Customize the look and feel of zernia image.","settings.theme":"App theme","settings.system":"System","settings.light":"Light","settings.dark":"Dark","settings.photoList":"Photo list","settings.thumbnailSize":"Default thumbnail size","settings.generalLead":"Manage language and startup behavior.","settings.language":"Language","settings.photoOpen":"Opening photos","settings.openImmersive":"Open photos in photo-only mode","settings.showInfo":"Show brief information in photo-only mode","settings.navigation":"Photo navigation","settings.loop":"Loop to the first photo after the last","settings.loopHint":"When off, navigation stops at the first and last photo.","settings.updates":"Automatic updates","settings.autoUpdate":"Check GitHub for updates at startup","settings.checking":"Checking…","settings.checkNow":"Check for updates now","settings.defaultApp":"Default app","settings.windowsPhoto":"Windows default photo app","settings.windowsPhotoHint":"Choose this app as the default photo viewer in Windows Settings.","settings.setDefault":"Set as default photo viewer","settings.associationHint":"JPG, PNG, APNG, WebP, AVIF, GIF, BMP, TIFF and ICO associations are registered during installation.","settings.startup":"Startup","settings.rememberLocation":"Remember last location","settings.history":"Recent history","settings.rememberRecent":"Remember recent photos and folders","settings.performanceLead":"Control memory and cache usage for large libraries.","settings.memory":"Memory cache","settings.thumbnailCache":"App cache","settings.cacheUsage":"{files} files · {size}","settings.clearCache":"Delete all cache","settings.clearingCache":"Deleting…","settings.cacheCleared":"Cache deleted.","settings.cacheError":"Could not delete cache.\n{details}","settings.aboutDescription":"A fast and beautiful desktop photo library","settings.version":"Version 0.1.7 · Tauri 2","settings.support":"Support the developer","settings.privacy":"Photos and metadata never leave this device.",
  "viewer.restore":"Return to normal view","viewer.minimize":"Minimize","viewer.maximize":"Maximize or restore","viewer.exit":"Exit app","viewer.close":"Close viewer","viewer.previous":"Previous photo","viewer.next":"Next photo","viewer.firstFrame":"First frame","viewer.previousFrame":"Previous frame","viewer.pause":"Pause (Space)","viewer.play":"Play (Space)","viewer.nextFrame":"Next frame","viewer.lastFrame":"Last frame","viewer.frameSeek":"Seek frames","viewer.frameNumber":"Frame number","viewer.frames":"frames","viewer.immersive":"Photo only","viewer.fit":"Fit to screen","viewer.zoomOut":"Zoom out","viewer.zoomIn":"Zoom in","viewer.rotate":"Rotate","viewer.flip":"Flip horizontally","viewer.info":"Photo information","viewer.fileSize":"File size","viewer.modified":"Modified","viewer.imageInfo":"Image information",
  "dialog.chooseFolder":"Select photo folder","dialog.chooseDestination":"Select destination folder","error.moveSome":"Some photos could not be moved.\n{details}","error.move":"Could not move photos.\n{details}","error.noImages":"No supported image files were found.","error.openDropped":"Could not open imported items.\n{details}","update.current":"You are using the latest version.","update.available":"Version {version} is available.\nDownload and install it now?","update.error":"Could not check for updates.\n{details}"
};

const ja: Dictionary = { ...en,
  "common.settings":"設定","common.close":"閉じる","common.image":"画像","common.images":"写真","common.ready":"準備完了","sidebar.navigation":"メインナビゲーション","sidebar.home":"ホーム","sidebar.recent":"最近の写真","sidebar.recentDisabled":"設定で履歴が無効になっています","sidebar.favorites":"お気に入り","sidebar.openFolder":"フォルダーを開く","sidebar.recentFolders":"最近のフォルダー","sidebar.removeRecent":"最近の一覧から削除","sidebar.removeRecentAria":"{path} を最近の履歴から削除","sidebar.collapse":"サイドバーを折りたたむ",
  "toolbar.recent":"最近の写真","toolbar.favorites":"お気に入り","toolbar.dropped":"読み込んだ写真","toolbar.library":"写真ライブラリ","toolbar.back":"戻る","toolbar.forward":"進む","toolbar.parent":"上のフォルダー","toolbar.move":"選択した写真を移動","toolbar.closeFolder":"現在のフォルダーを閉じる","toolbar.searchLabel":"ファイル名を検索","toolbar.search":"写真を検索","toolbar.sort":"並べ替え","toolbar.sortName":"名前順","toolbar.sortModified":"更新日時順","toolbar.sortCreated":"作成日時順","toolbar.sortSize":"サイズ順","toolbar.sortExtension":"形式順","toolbar.descending":"降順","toolbar.ascending":"昇順","toolbar.refresh":"更新","toolbar.list":"リスト表示","toolbar.grid":"グリッド表示","toolbar.details":"詳細パネル",
  "home.dropOpen":"ここにドロップして開く","home.dropDescription":"画像またはフォルダーを読み込みます","home.title":"写真を、もっと鮮明に。","home.description":"高速で静かな写真ライブラリ。\nすべての画像はこの端末内だけで処理されます。","home.browserNotice":"ブラウザプレビューではフォルダー選択を利用できません。","home.largeFolder":"大容量フォルダーに最適化","home.local":"完全なローカル処理","home.dropZone":"写真またはフォルダーをここにドロップ","home.openError":"フォルダーを開けません","home.retry":"再試行","home.photoCount":"写真 {count} 枚","home.selectedCount":"{count} 件選択","home.thumbnail":"サムネイル","gallery.empty":"検索結果がありません","gallery.tryAnother":"別の検索語を入力してください。","thumb.noPreview":"プレビューなし","thumb.unfavorite":"お気に入りから削除","thumb.favorite":"お気に入りに追加","thumb.remove":"一覧から削除","thumb.removeKeep":"一覧から削除（原本は保持）",
  "details.title":"詳細情報","details.close":"詳細を閉じる","details.select":"写真を選択してください","details.selectHint":"ファイルと撮影情報を確認できます。","details.copy":"値をコピー","details.basic":"基本情報","details.filename":"ファイル名","details.format":"形式","details.size":"サイズ","details.path":"パス","details.image":"画像","details.resolution":"解像度","details.color":"カラー形式","details.camera":"カメラ","details.maker":"メーカー","details.model":"モデル","details.lens":"レンズ","details.capture":"撮影","details.shutter":"シャッター","details.aperture":"絞り","details.focal":"焦点距離",
  "settings.general":"一般","settings.appearance":"外観","settings.performance":"性能","settings.about":"情報","settings.appearanceLead":"zernia image の外観を設定します。","settings.theme":"アプリのテーマ","settings.system":"システム","settings.light":"ライト","settings.dark":"ダーク","settings.photoList":"写真一覧","settings.thumbnailSize":"既定のサムネイルサイズ","settings.generalLead":"言語と起動動作を管理します。","settings.language":"言語","settings.photoOpen":"写真を開く","settings.openImmersive":"写真を開くとき写真のみ表示","settings.showInfo":"写真のみ表示で簡易情報を表示","settings.navigation":"写真の移動","settings.loop":"最後の写真の次に先頭へ戻る","settings.loopHint":"オフの場合、先頭と最後で移動が停止します。","settings.updates":"自動更新","settings.autoUpdate":"起動時に GitHub で更新を確認","settings.checking":"確認中…","settings.checkNow":"今すぐ更新を確認","settings.defaultApp":"既定のアプリ","settings.windowsPhoto":"Windows の既定の写真アプリ","settings.windowsPhotoHint":"Windows 設定でこのアプリを既定の写真ビューアーに選択できます。","settings.setDefault":"既定の写真ビューアーに設定","settings.associationHint":"JPG、PNG、APNG、WebP、AVIF、GIF、BMP、TIFF、ICO の関連付けはインストール時に登録されます。","settings.startup":"起動","settings.rememberLocation":"最後の場所を記憶","settings.history":"最近の履歴","settings.rememberRecent":"最近の写真とフォルダーを記憶","settings.performanceLead":"大規模ライブラリのメモリとキャッシュを調整します。","settings.memory":"メモリキャッシュ","settings.thumbnailCache":"サムネイルキャッシュ","settings.clearCache":"キャッシュを消去","settings.aboutDescription":"高速で美しいデスクトップ写真ライブラリ","settings.version":"バージョン 0.1.7 · Tauri 2","settings.support":"開発者を支援","settings.privacy":"写真とメタデータは端末の外へ送信されません。",
  "viewer.restore":"元の画面へ","viewer.minimize":"最小化","viewer.maximize":"最大化または元に戻す","viewer.exit":"アプリを終了","viewer.close":"ビューアーを閉じる","viewer.previous":"前の写真","viewer.next":"次の写真","viewer.firstFrame":"最初のフレーム","viewer.previousFrame":"前のフレーム","viewer.pause":"一時停止 (Space)","viewer.play":"再生 (Space)","viewer.nextFrame":"次のフレーム","viewer.lastFrame":"最後のフレーム","viewer.frameSeek":"フレーム移動","viewer.frameNumber":"フレーム番号","viewer.frames":"フレーム","viewer.immersive":"写真のみ表示","viewer.fit":"画面に合わせる","viewer.zoomOut":"縮小","viewer.zoomIn":"拡大","viewer.rotate":"回転","viewer.flip":"左右反転","viewer.info":"写真情報","viewer.fileSize":"ファイルサイズ","viewer.modified":"更新日時","viewer.imageInfo":"画像情報","dialog.chooseFolder":"写真フォルダーを選択","dialog.chooseDestination":"移動先フォルダーを選択","error.moveSome":"一部の写真を移動できませんでした。\n{details}","error.move":"写真を移動できませんでした。\n{details}","error.noImages":"対応する画像ファイルが見つかりません。","error.openDropped":"読み込んだ項目を開けません。\n{details}","update.current":"現在のバージョンは最新です。","update.available":"新しいバージョン {version} を利用できます。\n今すぐダウンロードしてインストールしますか？","update.error":"更新を確認できません。\n{details}"
};

const zhCN: Dictionary = { ...en,
  "common.settings":"设置","common.close":"关闭","common.image":"图片","common.images":"照片","common.ready":"就绪","sidebar.navigation":"主导航","sidebar.home":"主页","sidebar.recent":"最近照片","sidebar.recentDisabled":"设置中已关闭最近记录","sidebar.favorites":"收藏夹","sidebar.openFolder":"打开文件夹","sidebar.recentFolders":"最近文件夹","sidebar.removeRecent":"从最近列表中移除","sidebar.removeRecentAria":"从最近记录移除 {path}","sidebar.collapse":"折叠侧栏","toolbar.recent":"最近照片","toolbar.favorites":"收藏夹","toolbar.dropped":"导入的照片","toolbar.library":"照片库","toolbar.back":"后退","toolbar.forward":"前进","toolbar.parent":"上级文件夹","toolbar.move":"移动所选照片","toolbar.closeFolder":"关闭当前文件夹","toolbar.searchLabel":"按文件名搜索","toolbar.search":"搜索照片","toolbar.sort":"排序","toolbar.sortName":"按名称","toolbar.sortModified":"按修改日期","toolbar.sortCreated":"按创建日期","toolbar.sortSize":"按大小","toolbar.sortExtension":"按格式","toolbar.descending":"降序","toolbar.ascending":"升序","toolbar.refresh":"刷新","toolbar.list":"列表视图","toolbar.grid":"网格视图","toolbar.details":"详细信息面板",
  "home.dropOpen":"拖放到这里立即打开","home.dropDescription":"导入图片或文件夹","home.title":"让照片更加清晰。","home.description":"快速安静的照片库。\n所有图片仅在本设备处理。","home.browserNotice":"浏览器预览中无法选择文件夹。","home.largeFolder":"针对大型文件夹优化","home.local":"完全本地处理","home.dropZone":"将照片或文件夹拖放到这里","home.openError":"无法打开文件夹","home.retry":"重试","home.photoCount":"{count} 张照片","home.selectedCount":"已选择 {count} 项","home.thumbnail":"缩略图","gallery.empty":"没有搜索结果","gallery.tryAnother":"请尝试其他关键词。","thumb.noPreview":"无预览","thumb.unfavorite":"取消收藏","thumb.favorite":"添加收藏","thumb.remove":"从列表移除","thumb.removeKeep":"从列表移除（保留原文件）",
  "details.title":"详细信息","details.close":"关闭详细信息","details.select":"请选择照片","details.selectHint":"可以查看文件和拍摄信息。","details.copy":"复制值","details.basic":"基本信息","details.filename":"文件名","details.format":"格式","details.size":"大小","details.path":"路径","details.image":"图片","details.resolution":"分辨率","details.color":"颜色格式","details.camera":"相机","details.maker":"制造商","details.model":"型号","details.lens":"镜头","details.capture":"拍摄","details.shutter":"快门","details.aperture":"光圈","details.focal":"焦距",
  "settings.general":"常规","settings.appearance":"外观","settings.performance":"性能","settings.about":"关于","settings.appearanceLead":"设置 zernia image 的界面与风格。","settings.theme":"应用主题","settings.system":"跟随系统","settings.light":"浅色","settings.dark":"深色","settings.photoList":"照片列表","settings.thumbnailSize":"默认缩略图大小","settings.generalLead":"管理语言与启动行为。","settings.language":"语言","settings.photoOpen":"打开照片","settings.openImmersive":"打开照片时仅显示照片","settings.showInfo":"仅照片模式下显示简要信息","settings.navigation":"照片导航","settings.loop":"最后一张后循环到第一张","settings.loopHint":"关闭后将在第一张和最后一张停止。","settings.updates":"自动更新","settings.autoUpdate":"启动时从 GitHub 检查更新","settings.checking":"正在检查…","settings.checkNow":"立即检查更新","settings.defaultApp":"默认应用","settings.windowsPhoto":"Windows 默认照片应用","settings.windowsPhotoHint":"可在 Windows 设置中将此应用设为默认照片查看器。","settings.setDefault":"设为默认照片查看器","settings.associationHint":"JPG、PNG、APNG、WebP、AVIF、GIF、BMP、TIFF 和 ICO 文件关联会在安装时注册。","settings.startup":"启动","settings.rememberLocation":"记住上次位置","settings.history":"最近记录","settings.rememberRecent":"记住最近照片和文件夹","settings.performanceLead":"调整大型照片库的内存和缓存使用。","settings.memory":"内存缓存","settings.thumbnailCache":"缩略图缓存","settings.clearCache":"清除缓存","settings.aboutDescription":"快速美观的桌面照片库","settings.version":"版本 0.1.7 · Tauri 2","settings.support":"支持开发者","settings.privacy":"照片和元数据不会离开本设备。",
  "viewer.restore":"返回原界面","viewer.minimize":"最小化","viewer.maximize":"最大化或还原","viewer.exit":"退出应用","viewer.close":"关闭查看器","viewer.previous":"上一张照片","viewer.next":"下一张照片","viewer.firstFrame":"第一帧","viewer.previousFrame":"上一帧","viewer.pause":"暂停 (Space)","viewer.play":"播放 (Space)","viewer.nextFrame":"下一帧","viewer.lastFrame":"最后一帧","viewer.frameSeek":"帧定位","viewer.frameNumber":"帧编号","viewer.frames":"帧","viewer.immersive":"仅显示照片","viewer.fit":"适合屏幕","viewer.zoomOut":"缩小","viewer.zoomIn":"放大","viewer.rotate":"旋转","viewer.flip":"水平翻转","viewer.info":"照片信息","viewer.fileSize":"文件大小","viewer.modified":"修改日期","viewer.imageInfo":"图片信息","dialog.chooseFolder":"选择照片文件夹","dialog.chooseDestination":"选择目标文件夹","error.moveSome":"部分照片无法移动。\n{details}","error.move":"无法移动照片。\n{details}","error.noImages":"未找到支持的图片文件。","error.openDropped":"无法打开导入的项目。\n{details}","update.current":"当前已是最新版本。","update.available":"发现新版本 {version}。\n是否立即下载并安装？","update.error":"无法检查更新。\n{details}"
};

const zhTW: Dictionary = { ...zhCN,
  "common.settings":"設定","common.close":"關閉","common.image":"圖片","common.images":"相片","common.ready":"就緒","sidebar.navigation":"主要導覽","sidebar.home":"首頁","sidebar.recent":"最近相片","sidebar.recentDisabled":"設定中已關閉最近記錄","sidebar.favorites":"我的最愛","sidebar.openFolder":"開啟資料夾","sidebar.recentFolders":"最近資料夾","sidebar.removeRecent":"從最近清單移除","sidebar.removeRecentAria":"從最近記錄移除 {path}","sidebar.collapse":"摺疊側邊欄","toolbar.recent":"最近相片","toolbar.favorites":"我的最愛","toolbar.dropped":"匯入的相片","toolbar.library":"相片庫","toolbar.back":"上一頁","toolbar.forward":"下一頁","toolbar.parent":"上層資料夾","toolbar.move":"移動所選相片","toolbar.closeFolder":"關閉目前資料夾","toolbar.searchLabel":"依檔名搜尋","toolbar.search":"搜尋相片","toolbar.sort":"排序","toolbar.sortName":"依名稱","toolbar.sortModified":"依修改日期","toolbar.sortCreated":"依建立日期","toolbar.sortSize":"依大小","toolbar.sortExtension":"依格式","toolbar.descending":"遞減","toolbar.ascending":"遞增","toolbar.refresh":"重新整理","toolbar.list":"清單檢視","toolbar.grid":"格狀檢視","toolbar.details":"詳細資料面板",
  "home.dropOpen":"拖放到這裡立即開啟","home.dropDescription":"匯入圖片或資料夾","home.title":"讓相片更加清晰。","home.description":"快速安靜的相片庫。\n所有圖片僅在本裝置處理。","home.browserNotice":"瀏覽器預覽中無法選擇資料夾。","home.largeFolder":"針對大型資料夾最佳化","home.local":"完全本機處理","home.dropZone":"將相片或資料夾拖放到這裡","home.openError":"無法開啟資料夾","home.retry":"重試","home.photoCount":"{count} 張相片","home.selectedCount":"已選取 {count} 項","home.thumbnail":"縮圖","gallery.empty":"沒有搜尋結果","gallery.tryAnother":"請嘗試其他關鍵字。","thumb.noPreview":"無預覽","thumb.unfavorite":"取消收藏","thumb.favorite":"加入收藏","thumb.remove":"從清單移除","thumb.removeKeep":"從清單移除（保留原始檔）",
  "details.title":"詳細資料","details.close":"關閉詳細資料","details.select":"請選擇相片","details.selectHint":"可查看檔案與拍攝資訊。","details.copy":"複製值","details.basic":"基本資訊","details.filename":"檔名","details.format":"格式","details.size":"大小","details.path":"路徑","details.image":"圖片","details.resolution":"解析度","details.color":"色彩格式","details.camera":"相機","details.maker":"製造商","details.model":"型號","details.lens":"鏡頭","details.capture":"拍攝","details.shutter":"快門","details.aperture":"光圈","details.focal":"焦距",
  "settings.general":"一般","settings.appearance":"外觀","settings.performance":"效能","settings.about":"關於","settings.appearanceLead":"設定 zernia image 的介面與風格。","settings.theme":"應用程式主題","settings.system":"跟隨系統","settings.light":"淺色","settings.dark":"深色","settings.photoList":"相片清單","settings.thumbnailSize":"預設縮圖大小","settings.generalLead":"管理語言與啟動行為。","settings.language":"語言","settings.photoOpen":"開啟相片","settings.openImmersive":"開啟相片時只顯示相片","settings.showInfo":"只顯示相片時顯示簡要資訊","settings.navigation":"相片導覽","settings.loop":"最後一張後循環到第一張","settings.loopHint":"關閉後會在第一張與最後一張停止。","settings.updates":"自動更新","settings.autoUpdate":"啟動時從 GitHub 檢查更新","settings.checking":"正在檢查…","settings.checkNow":"立即檢查更新","settings.defaultApp":"預設應用程式","settings.windowsPhoto":"Windows 預設相片應用程式","settings.windowsPhotoHint":"可在 Windows 設定中將此應用程式設為預設相片檢視器。","settings.setDefault":"設為預設相片檢視器","settings.associationHint":"JPG、PNG、APNG、WebP、AVIF、GIF、BMP、TIFF 與 ICO 檔案關聯會在安裝時註冊。","settings.startup":"啟動","settings.rememberLocation":"記住上次位置","settings.history":"最近記錄","settings.rememberRecent":"記住最近相片和資料夾","settings.performanceLead":"調整大型相片庫的記憶體與快取用量。","settings.memory":"記憶體快取","settings.thumbnailCache":"縮圖快取","settings.clearCache":"清除快取","settings.aboutDescription":"快速美觀的桌面相片庫","settings.version":"版本 0.1.7 · Tauri 2","settings.support":"支持開發者","settings.privacy":"相片與中繼資料不會離開本裝置。",
  "viewer.restore":"返回原畫面","viewer.minimize":"最小化","viewer.maximize":"最大化或還原","viewer.exit":"結束應用程式","viewer.close":"關閉檢視器","viewer.previous":"上一張相片","viewer.next":"下一張相片","viewer.firstFrame":"第一幀","viewer.previousFrame":"上一幀","viewer.pause":"暫停 (Space)","viewer.play":"播放 (Space)","viewer.nextFrame":"下一幀","viewer.lastFrame":"最後一幀","viewer.frameSeek":"幀定位","viewer.frameNumber":"幀編號","viewer.frames":"幀","viewer.immersive":"只顯示相片","viewer.fit":"符合螢幕","viewer.zoomOut":"縮小","viewer.zoomIn":"放大","viewer.rotate":"旋轉","viewer.flip":"水平翻轉","viewer.info":"相片資訊","viewer.fileSize":"檔案大小","viewer.modified":"修改日期","viewer.imageInfo":"圖片資訊","dialog.chooseFolder":"選擇相片資料夾","dialog.chooseDestination":"選擇目標資料夾","error.moveSome":"部分相片無法移動。\n{details}","error.move":"無法移動相片。\n{details}","error.noImages":"找不到支援的圖片檔案。","error.openDropped":"無法開啟匯入的項目。\n{details}","update.current":"目前已是最新版本。","update.available":"發現新版本 {version}。\n是否立即下載並安裝？","update.error":"無法檢查更新。\n{details}"
};

const koHani: Dictionary = { ...ko,
  "common.settings":"設定","common.ready":"準備됨","sidebar.navigation":"基本 探索","sidebar.home":"홈","sidebar.recent":"最近 寫眞","sidebar.recentDisabled":"設定에서 最近 記錄이 꺼져 있습니다","sidebar.favorites":"즐겨찾기","sidebar.openFolder":"폴더 열기","sidebar.recentFolders":"最近 폴더","sidebar.removeRecent":"最近 目錄에서 削除","sidebar.collapse":"사이드바 접기","toolbar.recent":"最近 寫眞","toolbar.dropped":"가져온 寫眞","toolbar.library":"寫眞 라이브러리","toolbar.move":"選擇한 寫眞 移動","toolbar.closeFolder":"現在 폴더 닫기","toolbar.search":"寫眞 檢索","toolbar.sortModified":"修正 日期順","toolbar.sortCreated":"生成 日期順","toolbar.sortSize":"크기順","toolbar.sortExtension":"形式順","toolbar.details":"詳細情報 패널",
  "home.dropOpen":"여기에 놓아 바로 열기","home.dropDescription":"이미지 또는 폴더를 가져옵니다","home.title":"寫眞을, 더 鮮明하게.","home.description":"빠르고 조용한 寫眞 라이브러리.\n모든 이미지는 이 機器 안에서만 處理됩니다.","home.largeFolder":"大容量 폴더 最適化","home.local":"完全한 로컬 處理","home.dropZone":"寫眞 또는 폴더를 여기에 놓으세요","home.openError":"폴더를 열 수 없습니다","home.photoCount":"寫眞 {count}개","home.selectedCount":"{count}개 選擇됨","gallery.empty":"檢索 結果가 없습니다","gallery.tryAnother":"다른 檢索語를 入力해 보세요.","details.title":"詳細情報","details.select":"寫眞을 選擇하세요","details.selectHint":"파일과 撮影 情報를 確認할 수 있습니다.","details.basic":"基本 情報","details.filename":"파일名","details.format":"形式","details.size":"크기","details.path":"經路","details.image":"이미지","details.resolution":"解像度","details.color":"色相 形式","details.camera":"카메라","details.maker":"製造社","details.capture":"撮影","details.focal":"焦點 距離",
  "settings.general":"一般","settings.appearance":"模樣","settings.performance":"性能","settings.about":"情報","settings.appearanceLead":"zernia image의 畵面과 雰圍氣를 設定합니다.","settings.theme":"앱 主題","settings.system":"시스템","settings.photoList":"寫眞 目錄","settings.thumbnailSize":"基本 썸네일 크기","settings.generalLead":"言語와 始作 動作을 管理합니다.","settings.language":"言語","settings.photoOpen":"寫眞 열기","settings.openImmersive":"寫眞을 열 때 寫眞만 보기","settings.showInfo":"寫眞만 보기에서 簡單한 情報 表示","settings.navigation":"寫眞 移動","settings.loop":"마지막 寫眞 다음에 첫 寫眞으로 循環","settings.loopHint":"끄면 첫 寫眞과 마지막 寫眞에서 더 以上 移動하지 않습니다.","settings.updates":"自動 更新","settings.autoUpdate":"始作할 때 GitHub에서 更新 確認","settings.checking":"確認 中…","settings.checkNow":"지금 更新 確認","settings.defaultApp":"基本 앱","settings.windowsPhoto":"Windows 基本 寫眞 앱","settings.windowsPhotoHint":"Windows 設定에서 이 앱을 基本 寫眞 뷰어로 選擇할 수 있습니다.","settings.setDefault":"基本 寫眞 뷰어로 設定","settings.startup":"始作","settings.rememberLocation":"마지막 位置 記憶","settings.history":"最近 記錄","settings.rememberRecent":"最近 寫眞과 폴더 記錄","settings.performanceLead":"큰 라이브러리의 메모리와 캐시 使用量을 調節합니다.","settings.memory":"메모리 캐시","settings.thumbnailCache":"썸네일 캐시","settings.clearCache":"캐시 비우기","settings.aboutDescription":"빠르고 아름다운 데스크톱 寫眞 라이브러리","settings.version":"版 0.1.7 · Tauri 2","settings.support":"開發者 後援하기","settings.privacy":"寫眞과 메타데이터는 機器 밖으로 傳送되지 않습니다.",
  "viewer.restore":"原來 畵面으로","viewer.exit":"앱 終了","viewer.previous":"以前 寫眞","viewer.next":"다음 寫眞","viewer.immersive":"寫眞만 보기","viewer.fit":"畵面 맞춤","viewer.rotate":"回轉","viewer.flip":"左右 反轉","viewer.info":"寫眞 情報","viewer.fileSize":"파일 크기","viewer.modified":"修正한 日期","viewer.imageInfo":"이미지 情報","dialog.chooseFolder":"寫眞 폴더 選擇","dialog.chooseDestination":"寫眞을 移動할 폴더 選擇","update.current":"現在 最新 版을 使用하고 있습니다.","update.available":"새 版 {version}을 使用할 수 있습니다.\n지금 다운로드하고 設置할까요?","update.error":"更新을 確認할 수 없습니다.\n{details}"
};

const dictionaries: Record<Language, Dictionary> = { ko, en, ja, "zh-CN": zhCN, "zh-TW": zhTW, "ko-Hani": koHani };
const releaseOverrides: Record<Language, Partial<Dictionary>> = {
  ko: { "settings.animationControls": "움짤 재생 표시줄 표시", "settings.tabDetails": "Tab 키로 상세정보 열기/닫기", "settings.version": "버전 0.1.7 · Tauri 2" },
  en: { "settings.animationControls": "Show animated image controls", "settings.tabDetails": "Use Tab to toggle photo details", "settings.version": "Version 0.1.7 · Tauri 2" },
  ja: { "settings.animationControls": "アニメーション再生バーを表示", "settings.tabDetails": "Tab キーで写真情報を開閉", "settings.thumbnailCache": "アプリキャッシュ", "settings.cacheUsage": "{files} ファイル · {size}", "settings.clearCache": "すべてのキャッシュを削除", "settings.clearingCache": "削除中…", "settings.cacheCleared": "キャッシュを削除しました。", "settings.cacheError": "キャッシュを削除できませんでした。\n{details}", "settings.version": "バージョン 0.1.7 · Tauri 2" },
  "zh-CN": { "settings.animationControls": "显示动图播放栏", "settings.tabDetails": "使用 Tab 键开关照片详情", "settings.thumbnailCache": "应用缓存", "settings.cacheUsage": "{files} 个文件 · {size}", "settings.clearCache": "删除全部缓存", "settings.clearingCache": "正在删除…", "settings.cacheCleared": "缓存已删除。", "settings.cacheError": "无法删除缓存。\n{details}", "settings.version": "版本 0.1.7 · Tauri 2" },
  "zh-TW": { "settings.animationControls": "顯示動圖播放列", "settings.tabDetails": "使用 Tab 鍵開關相片詳細資料", "settings.thumbnailCache": "應用程式快取", "settings.cacheUsage": "{files} 個檔案 · {size}", "settings.clearCache": "刪除全部快取", "settings.clearingCache": "刪除中…", "settings.cacheCleared": "快取已刪除。", "settings.cacheError": "無法刪除快取。\n{details}", "settings.version": "版本 0.1.7 · Tauri 2" },
  "ko-Hani": { "settings.animationControls": "움짤 再生 表示줄 表示", "settings.tabDetails": "Tab 키로 詳細情報 열기/닫기", "settings.thumbnailCache": "앱 캐시", "settings.cacheUsage": "現在 {files}개 파일 · {size}", "settings.clearCache": "全體 캐시 削除", "settings.clearingCache": "削除 中…", "settings.cacheCleared": "캐시를 削除했습니다.", "settings.cacheError": "캐시를 削除하지 못했습니다.\n{details}", "settings.version": "版 0.1.7 · Tauri 2" }
};

export const languageOptions: { value: Language; label: string }[] = [
  { value: "ko", label: "한국어" }, { value: "en", label: "English" }, { value: "ja", label: "日本語" },
  { value: "zh-CN", label: "简体中文" }, { value: "zh-TW", label: "繁體中文" }, { value: "ko-Hani", label: "國漢文混用" }
];

export function translate(language: Language, key: TranslationKey, variables?: Record<string, string | number>): string {
  let value = releaseOverrides[language]?.[key] ?? dictionaries[language]?.[key] ?? ko[key];
  if (variables) for (const [name, replacement] of Object.entries(variables)) value = value.replaceAll(`{${name}}`, String(replacement));
  return value;
}

export function storedLanguage(): Language {
  try {
    const value = JSON.parse(localStorage.getItem("zernia.settings") ?? "{}").language;
    return typeof value === "string" && value in dictionaries ? value as Language : "ko";
  } catch { return "ko"; }
}

export function useI18n() {
  const language = useAppStore(state => state.settings.language);
  return (key: TranslationKey, variables?: Record<string, string | number>) => translate(language, key, variables);
}

export function languageLocale(language: Language): string {
  return ({ ko: "ko-KR", en: "en-US", ja: "ja-JP", "zh-CN": "zh-CN", "zh-TW": "zh-TW", "ko-Hani": "ko-KR" } as const)[language];
}
